#!/bin/bash
set -e

export BOTTLE_PORT=8080
export BOTTLE_HOST=0.0.0.0
export BOTTLE_ROOT=${JUPYTERHUB_SERVICE_PREFIX}proxy/${BOTTLE_PORT}/
export BOTTLE_RELOADER=0        # the reloader forks; it does not belong here
export BOTTLE_DEBUG=0

export DB_NAME=sem2026_nejczi
export DB_HOST=baza.fmf.uni-lj.si
export DB_USER=javnost
export DB_PASSWORD=javnogeslo
export DB_PORT=443

export SECRET_KEY=$(python -c "import secrets; print(secrets.token_hex(16))")

python app.py > /tmp/zerorisk.log 2>&1 &
exec "$@"