name: Run Insert Asset Script

on:
  schedule:
    - cron: "32 15 * * *"   # 17:30 Slovenia (UTC+2)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - name: Run insert_asset
        run: python Data/data_insert/insert_asset.py 
